---
title: "R skills assessment"
author: "Fabrizio Di Massimo"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: false
    keep_md: true
    path: "main/R-skills-assessment.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic stats

### **1. Summary statistics of GDP per capita by region**

```{r}

tag      <- "202311081903"
base_url <- "https://github.com/randrescastaneda/pub_data/raw/"
data_url <- paste0(base_url, tag, "/data/Rtest1/")


wdi <-
  readr::read_rds(paste0(data_url, "wdi_in1.Rds"))
```

```{r, results = 'hide'}
suppressMessages(library(dplyr))
library(dplyr)
options(dplyr.summarise.inform = FALSE)

# Function to calculate the weighted standard deviation
weighted_sd <- function(x, w) {
  complete_cases <- complete.cases(x, w)
  x <- x[complete_cases]
  w <- w[complete_cases]

  w_mean <- sum(x * w) / sum(w)
  w_variance <- sum(w * (x - w_mean)^2) / sum(w)
  w_std_dev <- sqrt(w_variance)
  
  return(w_std_dev)
}

regional_gdp_pc <- wdi %>%
  group_by(date, region) %>%
  summarise(
    Mean = round(sum(gdp * pop, na.rm = TRUE) / sum(pop, na.rm = TRUE)),
    N = n(),
    SD = round(weighted_sd(gdp, pop)),
    Min = round(min(gdp, na.rm = TRUE)),
    Max = round(max(gdp, na.rm = TRUE))
  ) %>%
  rename(year = date) %>%
  arrange(region, year) %>%
  select(region, everything())

# Comparison
results1 <- readr::read_rds(paste0(data_url, "wdi_summ_out.Rds"))

comparison <- waldo::compare(regional_gdp_pc, results1)
comparison
```

### **2. Aggregate stats**

```{r, results = 'hide'}

regional_gdp_pc_mean <- wdi %>%
  group_by(date, region) %>%
  summarise(
    pop_region = sum(pop, na.rm = TRUE),
    lifeex = round(sum(lifeex * pop, na.rm = TRUE) / pop_region, 3),
    gdp = round(sum(gdp * pop, na.rm = TRUE) / sum(pop, na.rm = TRUE), 3),
    pov_intl = round(sum(pov_intl * pop, na.rm = TRUE) / pop_region, 3)
    ) %>%
  mutate(estimate = "mean") %>%
  rename(year = date) %>%
  arrange(region, year) %>%
  select(estimate, region, everything())


regional_gdp_pc_sd <- wdi %>%
  group_by(date, region) %>%
  summarise(
    pop_region = sum(pop, na.rm = TRUE),
    lifeex = round(weighted_sd(lifeex, pop), 3),
    gdp = round(weighted_sd(gdp, pop), 3),
    pov_intl = round(weighted_sd(pov_intl, pop), 3)
    ) %>%
  mutate(estimate = "sd") %>%
  rename(year = date) %>%
  arrange(region, year) %>%
  select(estimate, region, everything())


regional_gdp_pc_min <- wdi %>%
  group_by(date, region) %>%
  summarise(
    pop_region = sum(pop, na.rm = TRUE),
    lifeex = round(min(lifeex, na.rm = TRUE), 3),
    gdp = round(min(gdp, na.rm = TRUE), 3),
    pov_intl = round(min(pov_intl, na.rm = TRUE), 3)
    ) %>%
  mutate(estimate = "min") %>%
  rename(year = date) %>%
  arrange(region, year) %>%
  select(estimate, region, everything())


regional_gdp_pc_max <- wdi %>%
  group_by(date, region) %>%
  summarise(
    pop_region = sum(pop, na.rm = TRUE),
    lifeex = round(max(lifeex, na.rm = TRUE), 3),
    gdp = round(max(gdp, na.rm = TRUE), 3),
    pov_intl = round(max(pov_intl, na.rm = TRUE), 3)
    ) %>%
  mutate(estimate = "max") %>%
  rename(year = date) %>%
  arrange(region, year) %>%
  select(estimate, region, everything())


# Function to calculate the weighted median
weighted.median <- function(x, w) {
  w <- w[order(x)]
  x <- x[order(x)]

  prob <- cumsum(w) / sum(w)
  ps <- which(abs(prob - 0.5) == min(abs(prob - 0.5)))
  return(x[ps])
}


regional_gdp_pc_med <- wdi %>%
  group_by(date, region) %>%
  summarise(
    pop_region = sum(pop, na.rm = TRUE),
    lifeex = round(weighted.median(lifeex, pop), 3),
    gdp = round(weighted.median(gdp, pop), 3),
    pov_intl = round(weighted.median(pov_intl, pop), 3)
    ) %>%
  mutate(estimate = "median") %>%
  rename(year = date) %>%
  arrange(region, year) %>%
  select(estimate, region, everything())

# Data frames union
agg_stats <- rbind(regional_gdp_pc_mean, regional_gdp_pc_sd, regional_gdp_pc_min, regional_gdp_pc_max, regional_gdp_pc_med)


# Comparison
results2 <- readr::read_rds(paste0(data_url, "wdi_agg_out.Rds"))

comparison <- waldo::compare(agg_stats, results2)
comparison
```

### **3. Find outliers**

```{r, results = 'hide'}

# Identifying outliers above and below 2.5 standard deviations

outliers <- wdi %>%
  group_by(date) %>%
  mutate(
    mean_lifeex = weighted.mean(lifeex, pop, na.rm = TRUE),
    sd_lifeex = weighted_sd(lifeex, pop),
    hl_lifeex = ifelse(lifeex > mean_lifeex + 2.5 * sd_lifeex, TRUE, FALSE),
    ll_lifeex = ifelse(lifeex < mean_lifeex - 2.5 * sd_lifeex, TRUE, FALSE),
   
    mean_gdp = weighted.mean(gdp, pop, na.rm = TRUE),
    sd_gdp = weighted_sd(gdp, pop),
    hl_gdp = ifelse(gdp > mean_gdp + 2.5 * sd_gdp, TRUE, FALSE),
    ll_gdp = ifelse(gdp < mean_gdp - 2.5 * sd_gdp, TRUE, FALSE),
    
    mean_gini = weighted.mean(gini, pop, na.rm = TRUE),
    sd_gini = weighted_sd(gini, pop),
    hl_gini = ifelse(gini > mean_gini + 2.5 * sd_gini, TRUE, FALSE),
    ll_gini = ifelse(gini < mean_gini - 2.5 * sd_gini, TRUE, FALSE)
    )


# Comparison
results3 <- readr::read_rds(paste0(data_url, "wdi_outliers_out.Rds"))

comparison <- waldo::compare(outliers, results3)
comparison


# Graph
library(ggplot2)

ggplot(outliers, aes(x = date, y = lifeex, color = region)) +
  geom_point() +
  geom_ribbon(data = outliers, aes(y = mean_lifeex, ymin = mean_lifeex - 2.5 * sd_lifeex, ymax = mean_lifeex + 2.5 * sd_lifeex), alpha = 0.2, fill = "darkgray", color = NA) +
  geom_line(data = outliers, aes(y = mean_lifeex), color = "blue", linewidth = 0.3) +
  labs(x = "date",
       y = "mean_lifeex") +
  theme_minimal() +
  theme(legend.direction = "horizontal",
        legend.position = c(0.5, 0.15)) +
  guides(color = guide_legend(title = NULL))

```

## Simulated data

```{r, results = 'hide'}
tag      <- "202311081903"
base_url <- "https://github.com/randrescastaneda/pub_data/raw/"
data_url <- paste0(base_url, tag, "/data/Rtest1/")

l_svy <-
    readr::read_rds(paste0(data_url, "svy_sim_in1.Rds"))
```

### **4. Poverty measures**

```{r, results = 'hide'}

# Define poverty lines
poverty_lines <- c(2.15, 3.65, 6.85)

# Function to calculate poverty estimates
calculate_poverty <- function(df, poverty_lines) {
  result <- lapply(poverty_lines, function(line) {
    df %>%
      summarise(
        headcount = sum(weight * (income < line)) / sum(weight),
        povgap = sum(weight * pmax(0, (line - income) / line)) / sum(weight),
        povseverity = sum(weight * pmax(0, (line - income) / line)^2) / sum(weight)
        ) %>%
      mutate(pov_line = line)
  })
  return(bind_rows(result, .id = "year"))
}

# Calculate poverty estimates for each dataset per year
poverty_estimates <- lapply(names(l_svy), function(year) calculate_poverty(l_svy[[year]], poverty_lines))

# Final result
names(poverty_estimates) <- 2001:2010

# Combine into one dataframe
poverty <- do.call(rbind, poverty_estimates)
poverty$year <- as.numeric(gsub("\\..*", "", rownames(poverty)))
rownames(poverty) <- NULL
poverty <- poverty[, c("year", "pov_line", "headcount", "povgap", "povseverity")]


# Comparison
results4 <- readr::read_rds(paste0(data_url, "dt_pov_out.Rds"))

comparison <- waldo::compare(poverty, results4)
comparison


# Graph
ggplot(poverty, aes(x = year, y = headcount, color = factor(pov_line))) +
  geom_line() +
  geom_point() +
  labs(x = "year", y = "headcount") +
  theme_minimal() +
  theme(legend.direction = "horizontal",
        legend.position = "bottom") +
  guides(color = guide_legend(title = NULL))

```

### **5. Lorenz curve**

```{r, results = 'hide'}

calculate_lorenz_curve <- function(l_svy) {
  lorenz_curves <- lapply(names(l_svy), function(year) {
    df <- l_svy[[year]]
    year_num <- as.numeric(gsub("\\D", "", year))
    df <- df[order(df$income), ]  # Sort the data by income
    df$cumulative_share_income <- cumsum(df$income * df$weight) / sum(df$income * df$weight)
    df$cumulative_share_population <- cumsum(df$weight) / sum(df$weight)
    interpolated_income <- approx(df$cumulative_share_population, df$cumulative_share_income, n = 100)
    bins <- seq(1/100, 1, length.out = 100)
    bins_int <- as.integer(bins * 100)
    data.frame(
      welfare = interpolated_income$y,
      cum_welfare = interpolated_income$y * bins,
      cum_population = bins,
      year = rep(year_num, 100),
      bin = bins_int
    )
  })
  return(do.call(rbind, lorenz_curves))
}

# Calculate Lorenz curves for each year from 2001 to 2010
lorenz_curves <- calculate_lorenz_curve(l_svy)
lorenz_curves$cum_population <- sprintf("%.17f", lorenz_curves$cum_population)
lorenz_curves$welfare <- sprintf("%.17f", lorenz_curves$welfare)
lorenz_curves$cum_welfare <- sprintf("%.17f", lorenz_curves$cum_welfare)


# Comparison
results5 <- readr::read_rds(paste0(data_url, "dt_lorenz_out.Rds"))

comparison <- waldo::compare(lorenz_curves, results5)
comparison


# Graph
library(ggplot2)

# Graficar las curvas de Lorenz
ggplot(lorenz_curves, aes(x = as.numeric(cum_population), y = as.numeric(cum_welfare), group = year, color = factor(year))) +
  geom_line() +
  labs(x = "cum_population", y = "cum_welfare") +
  theme_minimal() +
  scale_x_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1.00)) +
  scale_y_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1.00)) +
  guides(color = guide_legend(title = NULL)) +
  theme(legend.position = c(0.1, 0.57))

```

### **6. Gini coefficient**

```{r, results = 'hide'}

# Function to calculate Gini coefficient
calculate_gini <- function(l_svy) {
  gini_values <- lapply(l_svy, function(year_data) {
    # Sorting data by income
    sorted_data <- year_data[order(year_data$income), ]

    # Calculate cumulative sums
    cum_income <- cumsum(sorted_data$income * sorted_data$weight)
    total_income <- sum(sorted_data$income * sorted_data$weight)
    cum_population <- cumsum(sorted_data$weight)
    
    # Compute the coordinates of the Lorenz curve
    lorenz_x <- cum_population / sum(sorted_data$weight)
    lorenz_y <- cum_income / total_income

    # Calculate the area under the Lorenz curve using the trapezoidal rule
    gini_area <- sum((lorenz_x[-1] - lorenz_x[-length(lorenz_x)]) * 
                     (lorenz_y[-1] + lorenz_y[-length(lorenz_y)]) / 2)
    
    # Gini coefficient calculation
    gini <- 1 - 2 * gini_area
    return(gini)
  })

  return(gini_values)
}



# Calculate Gini coefficient for each year
gini_by_year <- calculate_gini(l_svy)

# Create a table with year and Gini coefficient
gini_table <- data.frame(year = 2001:2010, gini = unlist(gini_by_year))
rownames(gini_table) <- NULL


# Comparison
results6 <- readr::read_rds(paste0(data_url, "dt_gini_out.Rds"))

comparison <- waldo::compare(gini_table, results6)
comparison


# Graph
ggplot(gini_table, aes(x = year, y = gini, group = 1)) +
  geom_line() +
  geom_point() +
  labs(x = "year", y = "gini") +
  theme_minimal()
```
